/**
 * The code that drifts behind the site (§5.5). All of it is real, no lorem:
 * a compact 5-card poker hand evaluator, a counterfactual regret minimization
 * update, a pot-equity Monte Carlo run, and literal snippets copied from this
 * site's own components (src/components/*.tsx).
 */

export const POKER_EVALUATOR: string[] = [
  '// 5-card evaluator — [category, ...tiebreaks], higher wins',
  "const RANKS = '23456789TJQKA'",
  'type Card = { r: number; s: number }',
  '',
  'function parse(c: string): Card {',
  '  const r = RANKS.indexOf(c[0]) + 2',
  "  return { r, s: 'cdhs'.indexOf(c[1]) }",
  '}',
  '',
  'function evaluate5(cs: Card[]): number[] {',
  '  const rs = cs.map((c) => c.r).sort((a, b) => b - a)',
  '  const flush = cs.every((c) => c.s === cs[0].s)',
  "  const wheel = rs.join() === '14,5,4,3,2'",
  '  const run = rs.every((r, i) => !i || r === rs[i - 1] - 1)',
  '  const straight = run || wheel',
  '  const hi = wheel ? 5 : rs[0]',
  '  if (straight && flush) return [8, hi]',
  '  const seen = new Map<number, number>()',
  '  for (const r of rs) seen.set(r, (seen.get(r) ?? 0) + 1)',
  '  const groups = [...seen.entries()]',
  '    .sort((a, b) => b[1] - a[1] || b[0] - a[0])',
  '    .map(([r]) => r)',
  "  const shape = [...seen.values()].sort().reverse().join('')",
  "  if (shape === '41') return [7, ...groups] // quads",
  "  if (shape === '32') return [6, ...groups] // full house",
  '  if (flush) return [5, ...rs]',
  '  if (straight) return [4, hi]',
  "  if (shape === '311') return [3, ...groups] // set",
  "  if (shape === '221') return [2, ...groups] // two pair",
  "  if (shape === '2111') return [1, ...groups] // one pair",
  '  return [0, ...rs] // high card',
  '}',
]

export const CFR_UPDATE: string[] = [
  '// CFR — regret-matched strategy, one traversal update',
  'function cfr(n: Node, p0: number, p1: number): number {',
  '  if (n.terminal) return n.payoff()',
  '  const strat = regretMatch(n.regret)',
  '  const util = new Array<number>(n.actions).fill(0)',
  '  let nodeUtil = 0',
  '  for (let a = 0; a < n.actions; a++) {',
  '    util[a] = -cfr(n.next(a), p1, p0 * strat[a])',
  '    nodeUtil += strat[a] * util[a]',
  '  }',
  '  for (let a = 0; a < n.actions; a++) {',
  '    const regret = util[a] - nodeUtil',
  '    n.regret[a] += p1 * regret // weight by opp reach',
  '    n.stratSum[a] += p0 * strat[a]',
  '  }',
  '  return nodeUtil',
  '}',
  '',
  'function regretMatch(reg: number[]): number[] {',
  '  const pos = reg.map((r) => Math.max(r, 0))',
  '  const sum = pos.reduce((s, r) => s + r, 0)',
  '  if (sum <= 0) return pos.map(() => 1 / pos.length)',
  '  return pos.map((r) => r / sum) // play positive regret',
  '}',
]

export const POT_EQUITY: string[] = [
  '// Pot equity by Monte Carlo — deal the unseen, count wins',
  'function potEquity(hole: Card[], board: Card[], n = 2e4) {',
  '  const seen = new Set([...hole, ...board].map(key))',
  '  const deck = DECK.filter((c) => !seen.has(key(c)))',
  '  let win = 0',
  '  let tie = 0',
  '  for (let t = 0; t < n; t++) {',
  '    shuffle(deck)',
  '    const vill = deck.slice(0, 2)',
  '    const need = 5 - board.length',
  '    const run = board.concat(deck.slice(2, 2 + need))',
  '    const cmp = compare(best7(hole, run), best7(vill, run))',
  '    if (cmp > 0) win++',
  '    else if (cmp === 0) tie++',
  '  }',
  '  return (win + tie / 2) / n // share of the pot',
  '}',
  '',
  'function shuffle<T>(a: T[]) {',
  '  for (let i = a.length - 1; i > 0; i--) {',
  '    const j = Math.floor(Math.random() * (i + 1))',
  '    ;[a[i], a[j]] = [a[j], a[i]]',
  '  }',
  '}',
]

/** Copied verbatim (dedented) from this site's own components. */
export const SITE_SNIPPETS: string[] = [
  '// src/components/TypeLine.tsx',
  'const typeWord = (word: string, at: number) => {',
  '  if (at <= word.length) {',
  '    setText(word.slice(0, at))',
  '    schedule(() => typeWord(word, at + 1), 55 + Math.random() * 35)',
  '  } else {',
  '    schedule(() => deleteWord(word, word.length), 1600)',
  '  }',
  '}',
  '',
  '// src/components/Hero.tsx',
  "gsap.from('[data-hero-line] > span', {",
  '  yPercent: 112,',
  '  duration: 1.15,',
  "  ease: 'power3.out',",
  '  stagger: 0.09,',
  '  delay: 0.25,',
  '})',
  '',
  '// src/components/WhatWeDo.tsx',
  'const tl = gsap.timeline({',
  "  defaults: { ease: 'power3.out' },",
  '  scrollTrigger: {',
  '    trigger: section,',
  "    start: 'top top',",
  "    end: '+=250%',",
  '    pin: true,',
  '    scrub: 0.6,',
  '  },',
  '})',
  '',
  '// Flop, turn, river — scrubbed to fixed progress marks',
  'const marks = [0.22, 0.33, 0.44, 0.65, 0.85]',
  '',
  '// src/components/SectionIndex.tsx',
  '<div className="card-index" aria-hidden="true">',
  '  <span className="rank">{rank}</span>',
  '  <span className="suit">{suit}</span>',
  '</div>',
]

/** Everything the code layer draws, in reading order with breathing room. */
export const CODE_LINES: string[] = [
  ...POKER_EVALUATOR,
  '',
  ...CFR_UPDATE,
  '',
  ...POT_EQUITY,
  '',
  ...SITE_SNIPPETS,
  '',
]
